import Footer from './UI/Footer'
import Navbar from './UI/Navbar'
import './globals.scss'
import { Rubik } from 'next/font/google'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html
			lang='he'
			dir='rtl'
		>
			<body className={rubik.className}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	)
}

export default RootLayout
